### ISSUE TITLE
How can I use sql-cipher-adapter

### ISSUE THREAD

**Issue by firomero** [samikrc/CordovaSQLite#2]
I want to use an encrypted database, how can I open it?

**Comment by samikrc** [comment]
Hi,

I have looked into this briefly but decided to skip at the point I was 
developing this library, mostly because I did not need it. Essentially, 
it is possible: you will have to link to the corresponding libraries, 
and use the API for those libraries internally to talk to the database.

If you do end up extending this library to cover encrypted database, 
please issue a pull request and I will include the code.

Regards,
-Samik

**Comment by samikrc** [comment]
Closing.
